<a href="https://colab.research.google.com/github/iued-uni-heidelberg/corpusdev/blob/main/pr202502BundestagDownload.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Downloading Bundestag speech corpora
The project will download the csv file and will extract the field of speeches, which can be annotated and analysed using corpus tools.

In [ ]:
!wget https://zenodo.org/records/18177196/files/CPP-BT_2026-01-17_DE_CSV_Reden_Gesamt.zip?download=1
# !wget https://zenodo.org/records/18177196/files/CPP-BT_2026-01-17_DE_CSV_Reden_Metadaten.zip?download=1

In [2]:
!mv CPP-BT_2026-01-17_DE_CSV_Reden_Gesamt.zip?download=1 CPP-BT_2026-01-17_DE_CSV_Reden_Gesamt.zip
# !mv /content/CPP-BT_2026-01-17_DE_CSV_Reden_Metadaten.zip?download=1 /content/CPP-BT_2026-01-17_DE_CSV_Reden_Metadaten.zip

In [ ]:
!unzip CPP-BT_2026-01-17_DE_CSV_Reden_Gesamt.zip
# !unzip CPP-BT_2026-01-17_DE_CSV_Reden_Metadaten.zip

In [34]:
import pandas as pd
import xml.etree.ElementTree as ET

def indent(elem, level=0):
    i = "\n" + level * "  "
    if len(elem):
        if not elem.text or not elem.text.strip():
            elem.text = i + "  "
        if not elem.tail or not elem.tail.strip():
            elem.tail = i
        for elem in elem:
            indent(elem, level + 1)
        if not elem.tail or not elem.tail.strip():
            elem.tail = i
    else:
        if level and (not elem.tail or not elem.tail.strip()):
            elem.tail = i

def dataframe_to_xml(df, root_tag, row_tag, filename='output.xml'):
    """
    Converts a pandas DataFrame to an XML file.

    Args:
        df (pd.DataFrame): The input DataFrame.
        root_tag (str): The name for the root XML element.
        row_tag (str): The name for each row XML element.
        filename (str): The name of the output XML file.
    """
    root = ET.Element(root_tag)

    for index, row in df.iterrows():
        row_element = ET.SubElement(root, row_tag)
        for col_name, value in row.items():
            col_element = ET.SubElement(row_element, str(col_name))
            col_element.text = str(value)

    indent(root) # Apply indentation
    tree = ET.ElementTree(root)
    tree.write(filename, encoding='utf-8', xml_declaration=True)
    print(f"DataFrame successfully converted to {filename}")


'''
# Example usage with your 'df' DataFrame
# You might want to select a subset of your DataFrame for XML conversion if it's very large
# For demonstration, let's convert the first 5 rows of selected_columns
example_df = selected_columns.head(5)
dataframe_to_xml(example_df, 'speeches_data', 'speech', 'speeches.xml')

# To view the content of the generated XML file (optional)
with open('speeches.xml', 'r') as f:
    print(f.read())

'''

"\n# Example usage with your 'df' DataFrame\n# You might want to select a subset of your DataFrame for XML conversion if it's very large\n# For demonstration, let's convert the first 5 rows of selected_columns\nexample_df = selected_columns.head(5)\ndataframe_to_xml(example_df, 'speeches_data', 'speech', 'speeches.xml')\n\n# To view the content of the generated XML file (optional)\nwith open('speeches.xml', 'r') as f:\n    print(f.read())\n\n"

In [ ]:
# Load the CSV file into a pandas DataFrame
df = pd.read_csv('CPP-BT_2026-01-17_DE_CSV_Reden_Gesamt.csv')
# dfMD = pd.read_csv('CPP-BT_2026-01-17_DE_CSV_Reden_Metadaten.csv', low_memory=False)

# Display the first 5 rows to see the structure of the data
display(df.head())
# display(dfMD.head())

In [ ]:
display(df.head())

In [22]:
!head -n 10 CPP-BT_2026-01-17_DE_CSV_Reden_Gesamt.csv
# !head -n 10 /content/CPP-BT_2026-01-17_DE_CSV_Reden_Metadaten.csv

"doc_id","wahlperiode","sitzung_nr","sitzung_datum","sitzung_jahr","sitzung_start","sitzung_ende","sitzung_naechste","dokumentart","berichtart","protokoll_nr","protokoll_seite","sitzungstitel","sitzungstitel_zusatz","rede_id","rede_text","rede_zitate","rede_kommentare","redner_id","redner_titel","redner_vorname","redner_nachname","redner_namenszusatz","redner_ortszusatz","redner_fraktion","redner_rolle_kurz","redner_rolle_lang","zeichen","tokens","typen","saetze","version","doi_concept","doi_version","lizenz"
"18001.xml-0001",18,1,2013-10-22,2013,"11:00","15:01",NA,"Plenarprotokoll","Stenografischer Bericht","18/1",1,"1. Sitzung",NA,"ID1800100100","Herr Alterspräsident, ich schlage im Namen der CDU/CSU-Bundestagsfraktion unseren Kollegen Professor Dr. Norbert Lammert vor. Nun muss ich Ihnen einige Hinweise zum Wahlverfahren zumuten. Die Wahl findet mit verdeckten Stimmkarten, also geheim, statt. Gewählt ist, wer die Stimmen der Mehrheit der Mitglieder des Deutschen Bundestages, also mindestens 316 Stimmen, erhält. Für diese Wahl und für die spätere Wahl der Vizepräsidentinnen und Vizepräsidenten benötigen Sie Ihre Wahlausweise aus den Stimmkartenfächern in der Lobby. Für die Wahl des Präsidenten sind Wahlausweis und Stimmkarte gelb. Bitte kontrollieren Sie, ob dieser Wahlausweis Ihren Namen trägt. Die gelbe Stimmkarte und den amtlichen Wahlumschlag erhalten Sie nach Aufruf Ihres Namens von den Schriftführerinnen und Schriftführern an den Ausgabetischen hier oben links und rechts neben den Wahlkabinen. Ich bitte Sie, von Ihren Plätzen aus über die seitlichen Zugänge und nicht durch den Mittelgang zum Ausgabetisch zu gehen. Sie dürfen Ihre Stimmkarte nur in der Wahlkabine ankreuzen und müssen sie ebenfalls noch in der Wahlkabine in den Umschlag legen. Danach gehen Sie bitte zu den Wahlurnen hier vor dem Rednerpult. Die Schriftführerinnen und Schriftführer sind verpflichtet, jeden zurückzuweisen, der seine Stimmkarte außerhalb der Wahlkabine kennzeichnet oder in den Umschlag legt; die Stimmabgabe kann in diesem Fall jedoch vorschriftsmäßig wiederholt werden. Gültig sind nur Stimmkarten mit einem Kreuz bei „Ja“, „Nein“ oder „Erhalte mich“. – „Enthalte mich“. Ich enthalte mich nie; deshalb ist die Sache ja so schwierig. – Bevor Sie die Stimmkarte in eine der Wahlurnen werfen, übergeben Sie bitte Ihren Wahlausweis einem der Schriftführer an der Wahlurne. Die Abgabe des Wahlausweises dient als Nachweis für die Beteiligung an dieser Wahl und ersetzt die Eintragung in die Anwesenheitsliste – soweit Sie nicht ohnehin schon eingetragen sind. Ich bitte jetzt die eingeteilten Schriftführerinnen und Schriftführer, die vorgesehenen Plätze einzunehmen. Die beiden Schriftführer neben mir, Frau Barnett und Herr Koeppen, werden nun Ihre Namen in alphabetischer Reihenfolge aufrufen. Ich bitte Sie, den Namensaufruf zu verfolgen und sich nach dem Aufruf Ihres Namens zur Entgegennahme der Stimmkarte zu den Ausgabetischen vor den Wahlkabinen zu begeben. Haben alle Schriftführerinnen und Schriftführer ihre Plätze eingenommen? – Da ich nichts höre, nehme ich an, dass es so ist, und stelle fest: Es ist der Fall. Ich eröffne die Wahl und bitte Herrn Koeppen, mit dem Aufruf der Namen zu beginnen. Meine Damen und Herren, damit ist der Namensaufruf beendet. In wenigen Minuten werde ich nachfragen, ob alle ihre Stimme abgegeben haben. Dies gilt auch als Frage an die Schriftführerinnen und Schriftführer. Darf ich fragen, ob alle Mitglieder des Hauses ihre Stimme abgegeben haben? – Nein. Sehr gut. Darf ich noch einmal fragen, ob irgendein Mitglied des Hauses noch nicht Gelegenheit hatte, seine Stimme abzugeben? Das gilt auch für die Schriftführerinnen und Schriftführer. – Ich höre keinen Zuruf. Damit schließe ich die Wahl und bitte die Schriftführerinnen und Schriftführer, mit der Auszählung – – – Ich habe sie noch nicht ganz geschlossen. Der Satz war nicht fertig. Habt ihr es jetzt? – Wo ist der? – Ich werde den Abgeordneten jetzt nicht beim Namen nennen, gell, Peter? Das ist mein dritter Versuch. Hat noch irgendjemand seinen Stimmzettel nicht abgegeben? Wünscht noch irgendjemand, seinen Stimmzettel abzugeben? – Das ist jetzt wirklich nicht mehr der Fall. Ich höre keinen Widerspruch. Damit ist der Wahlgang geschlossen. Die Schriftführerinnen und Schriftführer bitte ich, mit der Auszählung zu beginnen. Zur Auszählung unterbreche ich die Sitzung für etwa 30 Minuten. Danach hören Sie das Klingelzeichen, das Sie kennen. Dann geht es weiter. Ich unterbreche die Sitzung. Das Protokoll über die Wahl des Präsidenten des 18. Deutschen Bundestages weist folgendes Ergebnis aus: abgegebene Stimmen 625; damit ist zugleich die Beschlussfähigkeit des 18. Deutschen Bundestages festgestellt. Ungültige Stimmen keine, gültige Stimmen 625. Mit Ja haben gestimmt 591. Korrekterweise teile ich Ihnen noch mit: Mit Nein haben gestimmt 26, Enthaltungen gab es 8. Dr. Norbert Lammert hat damit die erforderliche Mehrheit erhalten und ist zum Präsidenten des 18. Deutschen Bundestags gewählt. Herr Dr. Lammert, ich frage Sie: Nehmen Sie die Wahl an? Tagesordnungspunkt 3:","","(Beifall im ganzen Hause)|(Heiterkeit)|(Namensaufruf und Wahl)|(Zuruf: Nein!)|(Zurufe)|(Zuruf: Einer kommt noch!)|(Unterbrechung von 12.00 bis 12.22 Uhr)|(Anhaltender Beifall im ganzen Hause)|(Beifall im ganzen Hause)|(Beifall im ganzen Hause – Abgeordnete aller Fraktionen gratulieren dem Präsidenten)","11001074",NA,"Volker","Kauder",NA,NA,"CDU/CSU",NA,NA,4445,772,317,53,"2026-01-17","10.5281/zenodo.4542661","10.5281/zenodo.15462956","Creative Commons Zero 1.0 Universal"
"18001.xml-0002",18,1,2013-10-22,2013,"11:00","15:01",NA,"Plenarprotokoll","Stenografischer Bericht","18/1",1,"1. Sitzung",NA,"ID1800100200","Sehr geehrter Herr Präsident! Liebe Kolleginnen und Kollegen! Wir haben heute auch die Aufgabe, dem frisch gewählten Präsidenten entsprechende Stellvertreter zur Seite zu stellen, damit der weitere, aber auch der künftige Ablauf hier im Deutschen Bundestag in mehrfacher Hinsicht gewährleistet ist. Ihnen liegt dazu ein Antrag der CDU/CSU und der SPD vor, mit dem Inhalt, den der Präsident gerade skizziert hat. Wir schlagen darin vor, der SPD zwei Stellvertreter zuzuweisen, der Unionsfraktion ebenso und den beiden anderen Fraktionen, der Fraktion der Linken und der Grünen, jeweils einen Stellvertreter. Dieser Antrag entspricht dem Repräsentationsprinzip, das wir hier seit Jahrzehnten pflegen. Ich erinnere an 1994, als den Grünen kein Stellvertreter des Bundestagspräsidenten zugewiesen wurde und sich insbesondere meine Fraktion dafür eingesetzt hat, dass auch sie einen Stellvertreter stellen sollen. Denn wir waren der Auffassung: Jede Fraktion soll entsprechend ihrer Größe im Deutschen Bundestag im Präsidium vertreten sein. Infolgedessen bezieht sich unser Antrag auch auf die Mehrheitsverhältnisse im Deutschen Bundestag, die ja letztlich den Wählerwillen repräsentieren, und somit beinhaltet er jeweils zwei Stellvertreterpositionen für die Unionsfraktion und für die SPD. Ich möchte gerne darauf hinweisen, dass wir alle ein Interesse an einem starken Präsidium haben müssen. Das Bundestagspräsidium ist ein wichtiger Teil des Selbstverständnisses dieses Parlamentes. Gerade dann, wenn wir eine starke Regierung haben werden, muss es ein starkes Parlament zur Kontrolle und ein starkes Präsidium zur Leitung und zur Begleitung dieser Kontrolle geben. Die Aufgaben des Präsidiums sind vielfältig: Rechtsaufsicht, Repräsentation im In- und Ausland, Sitzungsleitung, Leitung von Kommissionen und nicht zuletzt natürlich auch das klare Wort, wie wir es vorhin auch in der Ansprache des frisch gewählten Präsidenten gehört haben. Die Kritik, die ich schon im Vorwege gehört habe, halte ich für falsch und ein Stück weit für kleinlich. Sieben stellvertretende Präsidenten in diesem Deutschen Bundestag sind nichts Neues; wir hatten sie in der vorletzten Legislaturperiode auch schon. – Sechs stellvertretende Präsidenten, pardon; insgesamt sieben Mitglieder des Präsidiums. Ich will auch darauf hinweisen, dass nach meiner Einschätzung – dies ging auch aus der Ansprache unseres frisch gewählten Bundestagspräsidenten hervor – weder die Arbeitsbelastung noch die Probleme, vor denen wir stehen, kleiner werden. Infolgedessen macht es Sinn, ein starkes Präsidium zu haben. Das bezieht sich auf den Umfang. Das bezieht sich auch auf die Persönlichkeiten, die sich hier zur Verfügung stellen. Ich sage es fraktionsübergreifend: Ich bin der Auffassung, dass wir nachher sehr respektable Kandidaten zur Auswahl haben. Deswegen bitte ich abschließend darum, diesem Antrag zuzustimmen. Lassen Sie uns gerne intensiv streiten über die richtigen Wege, über die richtige Politik in diesem Hause. Lassen Sie uns aber nicht um einen stellvertretenden Präsidentenposten streiten. Es gibt Wichtigeres: Die Aufgaben, die vor uns liegen, sind größer. Darüber müssen wir nicht nur ins Gespräch kommen, darüber müssen wir auch in Streit kommen – ich freue mich darauf –: unter der Führung und Leitung eines starken und guten Präsidiums. Herzlichen Dank.","","(Claudia Roth [Augsburg] [BÜNDNIS 90/DIE GRÜNEN]: Schäuble!)|(Britta Haßelmann [BÜNDNIS 90/DIE GRÜNEN]: Gut, dass wir schon ein bisschen weiter sind!)|(Claudia Roth [Augsburg] [BÜNDNIS 90/DIE GRÜNEN]: Sechs!)|(Beifall bei der CDU/CSU sowie bei Abgeordneten der SPD)|(Beifall bei der LINKEN)","11003541",NA,"Michael","Grosse-Brömer",NA,NA,"CDU/CSU",NA,NA,3344,547,271,26,"2026-01-17","10.5281/zenodo.4542661","10.5281/zenodo.15462956","Creative Commons Zero 1.0 Universal"
"18001.xml-0003",18,1,2013-10-22,2013,"11:00","15:01",NA,"Plenarprotokoll","Stenografischer Bericht","18/1",1,"1. Sitzung",NA,"ID1800100300","Danke. – Herr Präsident! Meine Damen und Herren! Herr Grosse-Brömer, Sie streuen hier Brotkrumen und locken uns ein bisschen in die falsche Richtung im Paragrafenwald der Geschäftsordnung. Sie haben quasi am Tag vor der konstituierenden Sitzung des Bundestages öffentlich bekannt gegeben, dass es mehr Vizepräsidentinnen und -präsidenten geben soll. Das wiederum war der Tag nach dem Beschluss über die Aufnahme von Koalitionsverhandlungen. Nun kann ich, was die öffentliche Wahrnehmung angeht, es manchen nicht verübeln, dass das als Geschmäckle, als Deal wahrgenommen wird. Das Zweite. Dies fällt mitten in die Debatte über die Sicherung der Minderheitenrechte der Opposition in diesem Parlament. Ich bedanke mich sehr herzlich für die klaren Worte des Bundestagspräsidenten zu diesen Fragen. Aber Ihre Geste wird von uns nicht als vertrauensbildende Maßnahme wahrgenommen. Festzuhalten bleibt doch – es ist eben gesagt worden –: Der Bundestag wird zurzeit nicht wesentlich größer. Die Aufgaben der Koalition werden nicht wesentlich größer. Im Gegenteil, Sie haben sogar den Vorzug, sich bezüglich ihrer Aufgaben eine wunderbare Arbeitsteilung zu schaffen. Aber die Aufgaben der Opposition werden gewaltig sein, und das bei weniger Abgeordneten. Mithin hat das Bundesverfassungsgericht mehrfach – das ist schon erwähnt worden – die besondere Rolle der Opposition für die Wahrung der freiheitlich-demokratischen Grundordnung betont. Es wird sogar von einer herausgehobenen Stellung der Opposition gesprochen. Das sollten wir uns vor diesem Hintergrund in diesem Hause noch einmal vergegenwärtigen. Nun senden Sie ein fragwürdiges Signal. Es geht nicht nur um einen Vizepräsidentenposten mehr. Es ist Ihr politischer Wille, von der bewährten Praxis in diesem Hause abzuweichen. Sie sagen, die Mehrheitsverhältnisse im Parlament sollten sich im Präsidium abbilden. Das könnte man so hinnehmen. Aber genau in dem entsprechenden Paragrafen der Geschäftsordnung des Bundestages wird überhaupt nicht darauf abgehoben, dass sich im Präsidium das Stärkeverhältnis der Fraktionen abbilden soll. Das ist in dem entsprechenden Paragrafen nicht enthalten. – Nein, Sie können gerne noch einmal nachlesen. Darüber können wir uns im Ältestenrat gerne streiten. Es gibt keinen Bezug auf das Berechnungsverfahren. Es gibt nur die Feststellung, die sich aus der sogenannten Grundmandatsregelung ergibt, dass jede Fraktion mit einem Vizepräsidenten im Präsidium vertreten sein soll. Das ist seit Jahren geübte Praxis in diesem Hause. Es geht um die Repräsentation des gesamten Hauses. Deshalb ist diese Praxis besser und demokratischer. Sie selber haben es vorhin erwähnt: Das, was wir infrage stellen, ist in der 13. Legislaturperiode auf Antrag der Bündnisgrünen eingeführt worden. Auch Sie haben damals als CDU/CDU und FDP ausdrücklich beantragt, dass die Anzahl der Stellvertreterinnen und Stellvertreter bzw. der Vizepräsidentinnen und Vizepräsidenten der Anzahl der Fraktionen entsprechen soll. Nun zur geübten Praxis. Abgesehen von der 1. Legislaturperiode, ist das Präsidium von der 2. bis einschließlich zur 15. Legislaturperiode mit fünf Mitgliedern besetzt gewesen. In der 14. Legislaturperiode waren es sechs. Damals gab es einen Präsidenten, zwei Vizepräsidenten der Koalition und drei Vizepräsidenten der Opposition. Erst in der 16. Legislaturperiode, also zur Zeit der Großen Koalition, ist man davon abgewichen, und es hat einen Vizepräsidenten bzw. eine Vizepräsidentin mehr gegeben. Nun nehmen Sie ausschließlich Bezug auf diese 16. Wahlperiode und gehen von dem zuvor – auch in der letzten Legislaturperiode – angewendeten Prinzip ab und wollen wieder sechs Stellvertreter. Auch damals hatte die SPD zwei Stellvertreter. So richtig geholfen hat es nicht. Das Wahlergebnis der SPD war nicht ganz überzeugend. Gerade erklären Sie von der SPD Ihrer Mitgliederschaft tapfer, dass erst das Ergebnis der Koalitionsverhandlungen darüber entscheidet, ob Sie eine Große Koalition eingehen. Aber den Vizepräsidentenposten wollen Sie schon heute in Anspruch nehmen. Was passiert denn dann, wenn Ihre Basis am Ende sagt: „Der Inhalt der Koalitionsvereinbarung reicht uns nicht; wir wollen keine Große Koalition eingehen“, mit diesem zusätzlichen Vizepräsidentenposten? Diese Frage sollte erlaubt sein. Wie Sie merken, ist vieles in diesem Zusammenhang unklar. Außerdem entsteht der Eindruck, dass es sich hier um eine willkürliche Praxis handelt. Sie klopfen sich sozusagen auf Ihre parlamentarische Brust und warten auf Großraumgeräusche. Wir finden das ziemlich kleingeistig. Ich finde, wir sollten an die gute parlamentarische Praxis anknüpfen. Es besteht auch aufgrund der konkreten Erfahrungen derjenigen, die schon Mitglied des Bundestages waren, überhaupt keine Veranlassung, die Zahl der Vizepräsidenten zu erhöhen. Die demokratische Führung der bisherigen Präsidien nach dem alten Prinzip war gut. Danke schön.","","(Beifall bei der LINKEN sowie bei Abgeordneten des BÜNDNISSES 90/DIE GRÜNEN)|(Beifall bei der LINKEN sowie bei Abgeordneten des BÜNDNISSES 90/DIE GRÜNEN)|(Beifall bei der LINKEN und dem BÜNDNIS 90/DIE GRÜNEN)|(Michael Grosse-Brömer [CDU/CSU]: Nein!)|(Dr. Günter Krings [CDU/CSU]: Doch!)|(Beifall bei der LINKEN sowie bei Abgeordneten des BÜNDNISSES 90/DIE GRÜNEN – Michael Grosse-Brömer [CDU/CSU]: Doch!)|(Michael Grosse-Brömer [CDU/CSU]: Mindestens!)|(Volker Kauder [CDU/CSU]: Nein, das stimmt nicht!)|(Beifall bei der LINKEN sowie bei Abgeordneten des BÜNDNISSES 90/DIE GRÜNEN)|(Heiterkeit und Beifall bei Abgeordneten der LINKEN)|(Beifall bei der LINKEN sowie bei Abgeordneten des BÜNDNISSES 90/DIE GRÜNEN)|(Widerspruch bei der SPD – Michael Grosse- Brömer [CDU/CSU]: Präsidium ist unabhängig davon!)|(Beifall bei der LINKEN sowie bei Abgeordneten des BÜNDNISSES 90/DIE GRÜNEN)|(Beifall bei der LINKEN und dem BÜNDNIS 90/DIE GRÜNEN)","11003848","Dr.","Petra","Sitte",NA,NA,"DIE LINKE",NA,NA,4908,800,368,59,"2026-01-17","10.5281/zenodo.4542661","10.5281/zenodo.15462956","Creative Commons Zero 1.0 Universal"
"18001.xml-0004",18,1,2013-10-22,2013,"11:00","15:01",NA,"Plenarprotokoll","Stenografischer Bericht","18/1",1,"1. Sitzung",NA,"ID1800100400","Herr Präsident! Meine Damen und Herren! Natürlich kann man darüber diskutieren, ob ein Präsidium zu groß oder zu klein ist; aber ich finde, dass ein Präsidium, das aus dem Präsidenten und den Stellvertretern besteht, also in diesem Fall aus sieben Personen bestehen soll, dass also ein siebenköpfiges Präsidium nicht unangemessen groß ist für ein Parlament aus 631 Abgeordneten. Bei der Bildung eines Präsidiums gibt es eigentlich drei Regeln, zwei ungeschriebene und eine, die in unserer Geschäftsordnung steht. In der Geschäftsordnung steht die Grundmandatsklausel. Die erste ungeschriebene Regel ist: Die stärkste Fraktion soll den Präsidenten stellen. Das ist eine Übung im Deutschen Bundestag, der wir immer gefolgt sind. Auch heute haben wir das gemacht. Die geschriebene Regel in der Geschäftsordnung des Deutschen Bundestages, die wir inzwischen angenommen haben, besagt: Jede Fraktion soll unabhängig von ihrer Größe einen Platz im Präsidium bekommen, also ein Grundmandat. Dieses Grundmandat schützt die kleinen Fraktionen. Es ist, wenn man so will, praktizierter Minderheitenschutz. Würde es diese Grundmandatsklausel übrigens nicht geben, wäre auch bei nur fünf Stellvertretern die Verteilung: CDU/CSU zwei, SPD zwei, Linke einer und Grüne null. Mit anderen Worten: Mit der Grundmandatsklausel sichern wir erst einmal die Beteiligung aller Fraktionen im Präsidium. Die dritte Regel ist, dass natürlich das Präsidium auch die Mehrheitsverhältnisse im Parlament abbilden muss. Deshalb werden manchmal ein, manchmal zwei Vizepräsidenten hinzugenommen, um diese Mehrheit darzustellen. Genau das ist hier der Fall: drei für die Union, zwei für die SPD und je einer für die Grünen und für die Linke. Wenn jetzt die geschätzten Kollegen und Kolleginnen von den Grünen sagen, dass im Verhältnis zu ihnen der SPD kein zweiter Vizepräsident zukommen solle, dann kann ich nur sagen: Wir haben beide wirklich nicht gut abgeschnitten bei der Bundestagswahl, aber 25,7 Prozent sind immer noch erkennbar mehr als 8,4 Prozent. Das muss ich den Grünen schon einmal sagen. Ungleiches gleich zu behandeln, ist kein Minderheitenschutz. Aber ich bin schon der Meinung – ich kann das hier für die SPD-Bundestagsfraktion erklären –: Wir sind ohne Einschränkungen gesprächsbereit, wenn es darum geht, die Rechte von Minderheiten im Deutschen Bundestag sicherzustellen, auch wenn wir im Falle der Bildung einer Großen Koalition nur zwei kleine Oppositionsfraktionen haben sollten. Eine parlamentarische Demokratie, die funktioniert, braucht nicht nur eine handlungsfähige Regierung, sondern auch eine effektive Opposition. Für mich ist völlig undenkbar, dass die Opposition nicht in der Lage sein sollte, Anhörungen zu beantragen, Untersuchungsausschüsse auf den Weg zu bringen oder ausreichend Redezeit zu bekommen. Wir werden darüber reden, und wir werden einen Konsens bekommen. Vielen Dank.","","(Beifall bei der SPD und der CDU/CSU)|(Widerspruch bei der LINKEN – Volker Kauder [CDU/CSU]: Ja! So ist es!)|(Beifall bei der SPD und der CDU/CSU)|(Beifall bei der SPD sowie bei Abgeordneten der CDU/CSU)|(Beifall bei der SPD und der CDU/CSU)","11003820",NA,"Thomas","Oppermann",NA,NA,"SPD",NA,NA,2881,485,237,24,"2026-01-17","10.5281/zenodo.4542661","10.5281/zenodo.15462956","Creative Commons Zero 1.0 Universal"

### Note on usage of the dataframes
To extract a specific field (column), you can access it by its name. For example, to get the 'speech_text' column, you would do the following:

In [7]:
# Replace 'speech_text' with the actual column name you want to extract
# You can also view all column names using `df.columns`
speech_texts = df['rede_text']

# Display the first few entries of the extracted field
display(speech_texts.head())

0    Herr Alterspräsident, ich schlage im Namen der...
1    Sehr geehrter Herr Präsident! Liebe Kolleginne...
2    Danke. – Herr Präsident! Meine Damen und Herre...
3    Herr Präsident! Meine Damen und Herren! Natürl...
4    Sehr geehrter Herr Präsident! Meine Damen und ...
Name: rede_text, dtype: object

In [9]:
print(df['rede_text'].dtype)

object

In [10]:
for i, speech_text in enumerate(df['rede_text']):
    print(f"Speech {i+1}: {speech_text[:200]}...") # Print first 200 characters of each speech
    if i >= 4: # Print only the first 5 speeches for demonstration
        break

Speech 1: Herr Alterspräsident, ich schlage im Namen der CDU/CSU-Bundestagsfraktion unseren Kollegen Professor Dr. Norbert Lammert vor. Nun muss ich Ihnen einige Hinweise zum Wahlverfahren zumuten. Die Wahl fin...
Speech 2: Sehr geehrter Herr Präsident! Liebe Kolleginnen und Kollegen! Wir haben heute auch die Aufgabe, dem frisch gewählten Präsidenten entsprechende Stellvertreter zur Seite zu stellen, damit der weitere, a...
Speech 3: Danke. – Herr Präsident! Meine Damen und Herren! Herr Grosse-Brömer, Sie streuen hier Brotkrumen und locken uns ein bisschen in die falsche Richtung im Paragrafenwald der Geschäftsordnung. Sie haben q...
Speech 4: Herr Präsident! Meine Damen und Herren! Natürlich kann man darüber diskutieren, ob ein Präsidium zu groß oder zu klein ist; aber ich finde, dass ein Präsidium, das aus dem Präsidenten und den Stellver...
Speech 5: Sehr geehrter Herr Präsident! Meine Damen und Herren! Liebe Kolleginnen und Kollegen, vor allen Dingen auch liebe neue Kolleginnen und Kollegen! Lassen Sie mich drei Vorbemerkungen machen. Zum einen g...

In [ ]:
for speech_text in df['rede_text'].head(): # Using .head() to limit output for demonstration
    print(f"Speech: {speech_text[:200]}...") # Print first 200 characters of each speech

In [25]:
# Access multiple columns by providing a list of column names
selected_columns = df[['rede_text', 'sitzung_datum', "redner_vorname","redner_nachname","redner_fraktion"]]

# Display the first few rows of the new DataFrame with selected columns
display(selected_columns.head())

,rede_text,sitzung_datum,redner_vorname,redner_nachname,redner_fraktion
0,"Herr Alterspräsident, ich schlage im Namen der...",2013-10-22,Volker,Kauder,CDU/CSU
1,Sehr geehrter Herr Präsident! Liebe Kolleginne...,2013-10-22,Michael,Grosse-Brömer,CDU/CSU
2,Danke. – Herr Präsident! Meine Damen und Herre...,2013-10-22,Petra,Sitte,DIE LINKE
3,Herr Präsident! Meine Damen und Herren! Natürl...,2013-10-22,Thomas,Oppermann,SPD
4,Sehr geehrter Herr Präsident! Meine Damen und ...,2013-10-22,Britta,Haßelmann,BÜNDNIS 90/DIE GRÜNEN

In [35]:
dataframe_to_xml(selected_columns, 'corpus', 'speech', filename='bundestag.xml')

DataFrame successfully converted to bundestag.xml

In [37]:
!head -n 50 bundestag.xml

<?xml version='1.0' encoding='utf-8'?>
<corpus>
  <speech>
    <rede_text>Herr Alterspräsident, ich schlage im Namen der CDU/CSU-Bundestagsfraktion unseren Kollegen Professor Dr. Norbert Lammert vor. Nun muss ich Ihnen einige Hinweise zum Wahlverfahren zumuten. Die Wahl findet mit verdeckten Stimmkarten, also geheim, statt. Gewählt ist, wer die Stimmen der Mehrheit der Mitglieder des Deutschen Bundestages, also mindestens 316 Stimmen, erhält. Für diese Wahl und für die spätere Wahl der Vizepräsidentinnen und Vizepräsidenten benötigen Sie Ihre Wahlausweise aus den Stimmkartenfächern in der Lobby. Für die Wahl des Präsidenten sind Wahlausweis und Stimmkarte gelb. Bitte kontrollieren Sie, ob dieser Wahlausweis Ihren Namen trägt. Die gelbe Stimmkarte und den amtlichen Wahlumschlag erhalten Sie nach Aufruf Ihres Namens von den Schriftführerinnen und Schriftführern an den Ausgabetischen hier oben links und rechts neben den Wahlkabinen. Ich bitte Sie, von Ihren Plätzen aus über die seitlichen Zugänge und nicht durch den Mittelgang zum Ausgabetisch zu gehen. Sie dürfen Ihre Stimmkarte nur in der Wahlkabine ankreuzen und müssen sie ebenfalls noch in der Wahlkabine in den Umschlag legen. Danach gehen Sie bitte zu den Wahlurnen hier vor dem Rednerpult. Die Schriftführerinnen und Schriftführer sind verpflichtet, jeden zurückzuweisen, der seine Stimmkarte außerhalb der Wahlkabine kennzeichnet oder in den Umschlag legt; die Stimmabgabe kann in diesem Fall jedoch vorschriftsmäßig wiederholt werden. Gültig sind nur Stimmkarten mit einem Kreuz bei „Ja“, „Nein“ oder „Erhalte mich“. – „Enthalte mich“. Ich enthalte mich nie; deshalb ist die Sache ja so schwierig. – Bevor Sie die Stimmkarte in eine der Wahlurnen werfen, übergeben Sie bitte Ihren Wahlausweis einem der Schriftführer an der Wahlurne. Die Abgabe des Wahlausweises dient als Nachweis für die Beteiligung an dieser Wahl und ersetzt die Eintragung in die Anwesenheitsliste – soweit Sie nicht ohnehin schon eingetragen sind. Ich bitte jetzt die eingeteilten Schriftführerinnen und Schriftführer, die vorgesehenen Plätze einzunehmen. Die beiden Schriftführer neben mir, Frau Barnett und Herr Koeppen, werden nun Ihre Namen in alphabetischer Reihenfolge aufrufen. Ich bitte Sie, den Namensaufruf zu verfolgen und sich nach dem Aufruf Ihres Namens zur Entgegennahme der Stimmkarte zu den Ausgabetischen vor den Wahlkabinen zu begeben. Haben alle Schriftführerinnen und Schriftführer ihre Plätze eingenommen? – Da ich nichts höre, nehme ich an, dass es so ist, und stelle fest: Es ist der Fall. Ich eröffne die Wahl und bitte Herrn Koeppen, mit dem Aufruf der Namen zu beginnen. Meine Damen und Herren, damit ist der Namensaufruf beendet. In wenigen Minuten werde ich nachfragen, ob alle ihre Stimme abgegeben haben. Dies gilt auch als Frage an die Schriftführerinnen und Schriftführer. Darf ich fragen, ob alle Mitglieder des Hauses ihre Stimme abgegeben haben? – Nein. Sehr gut. Darf ich noch einmal fragen, ob irgendein Mitglied des Hauses noch nicht Gelegenheit hatte, seine Stimme abzugeben? Das gilt auch für die Schriftführerinnen und Schriftführer. – Ich höre keinen Zuruf. Damit schließe ich die Wahl und bitte die Schriftführerinnen und Schriftführer, mit der Auszählung – – – Ich habe sie noch nicht ganz geschlossen. Der Satz war nicht fertig. Habt ihr es jetzt? – Wo ist der? – Ich werde den Abgeordneten jetzt nicht beim Namen nennen, gell, Peter? Das ist mein dritter Versuch. Hat noch irgendjemand seinen Stimmzettel nicht abgegeben? Wünscht noch irgendjemand, seinen Stimmzettel abzugeben? – Das ist jetzt wirklich nicht mehr der Fall. Ich höre keinen Widerspruch. Damit ist der Wahlgang geschlossen. Die Schriftführerinnen und Schriftführer bitte ich, mit der Auszählung zu beginnen. Zur Auszählung unterbreche ich die Sitzung für etwa 30 Minuten. Danach hören Sie das Klingelzeichen, das Sie kennen. Dann geht es weiter. Ich unterbreche die Sitzung. Das Protokoll über die Wahl des Präsidenten des 18. Deutschen Bundestages weist folgendes Ergebnis aus: abgegebene Stimmen 625; damit ist zugleich die Beschlussfähigkeit des 18. Deutschen Bundestages festgestellt. Ungültige Stimmen keine, gültige Stimmen 625. Mit Ja haben gestimmt 591. Korrekterweise teile ich Ihnen noch mit: Mit Nein haben gestimmt 26, Enthaltungen gab es 8. Dr. Norbert Lammert hat damit die erforderliche Mehrheit erhalten und ist zum Präsidenten des 18. Deutschen Bundestags gewählt. Herr Dr. Lammert, ich frage Sie: Nehmen Sie die Wahl an? Tagesordnungspunkt 3:</rede_text>
    <sitzung_datum>2013-10-22</sitzung_datum>
    <redner_vorname>Volker</redner_vorname>
    <redner_nachname>Kauder</redner_nachname>
    <redner_fraktion>CDU/CSU</redner_fraktion>
  </speech>
  <speech>
    <rede_text>Sehr geehrter Herr Präsident! Liebe Kolleginnen und Kollegen! Wir haben heute auch die Aufgabe, dem frisch gewählten Präsidenten entsprechende Stellvertreter zur Seite zu stellen, damit der weitere, aber auch der künftige Ablauf hier im Deutschen Bundestag in mehrfacher Hinsicht gewährleistet ist. Ihnen liegt dazu ein Antrag der CDU/CSU und der SPD vor, mit dem Inhalt, den der Präsident gerade skizziert hat. Wir schlagen darin vor, der SPD zwei Stellvertreter zuzuweisen, der Unionsfraktion ebenso und den beiden anderen Fraktionen, der Fraktion der Linken und der Grünen, jeweils einen Stellvertreter. Dieser Antrag entspricht dem Repräsentationsprinzip, das wir hier seit Jahrzehnten pflegen. Ich erinnere an 1994, als den Grünen kein Stellvertreter des Bundestagspräsidenten zugewiesen wurde und sich insbesondere meine Fraktion dafür eingesetzt hat, dass auch sie einen Stellvertreter stellen sollen. Denn wir waren der Auffassung: Jede Fraktion soll entsprechend ihrer Größe im Deutschen Bundestag im Präsidium vertreten sein. Infolgedessen bezieht sich unser Antrag auch auf die Mehrheitsverhältnisse im Deutschen Bundestag, die ja letztlich den Wählerwillen repräsentieren, und somit beinhaltet er jeweils zwei Stellvertreterpositionen für die Unionsfraktion und für die SPD. Ich möchte gerne darauf hinweisen, dass wir alle ein Interesse an einem starken Präsidium haben müssen. Das Bundestagspräsidium ist ein wichtiger Teil des Selbstverständnisses dieses Parlamentes. Gerade dann, wenn wir eine starke Regierung haben werden, muss es ein starkes Parlament zur Kontrolle und ein starkes Präsidium zur Leitung und zur Begleitung dieser Kontrolle geben. Die Aufgaben des Präsidiums sind vielfältig: Rechtsaufsicht, Repräsentation im In- und Ausland, Sitzungsleitung, Leitung von Kommissionen und nicht zuletzt natürlich auch das klare Wort, wie wir es vorhin auch in der Ansprache des frisch gewählten Präsidenten gehört haben. Die Kritik, die ich schon im Vorwege gehört habe, halte ich für falsch und ein Stück weit für kleinlich. Sieben stellvertretende Präsidenten in diesem Deutschen Bundestag sind nichts Neues; wir hatten sie in der vorletzten Legislaturperiode auch schon. – Sechs stellvertretende Präsidenten, pardon; insgesamt sieben Mitglieder des Präsidiums. Ich will auch darauf hinweisen, dass nach meiner Einschätzung – dies ging auch aus der Ansprache unseres frisch gewählten Bundestagspräsidenten hervor – weder die Arbeitsbelastung noch die Probleme, vor denen wir stehen, kleiner werden. Infolgedessen macht es Sinn, ein starkes Präsidium zu haben. Das bezieht sich auf den Umfang. Das bezieht sich auch auf die Persönlichkeiten, die sich hier zur Verfügung stellen. Ich sage es fraktionsübergreifend: Ich bin der Auffassung, dass wir nachher sehr respektable Kandidaten zur Auswahl haben. Deswegen bitte ich abschließend darum, diesem Antrag zuzustimmen. Lassen Sie uns gerne intensiv streiten über die richtigen Wege, über die richtige Politik in diesem Hause. Lassen Sie uns aber nicht um einen stellvertretenden Präsidentenposten streiten. Es gibt Wichtigeres: Die Aufgaben, die vor uns liegen, sind größer. Darüber müssen wir nicht nur ins Gespräch kommen, darüber müssen wir auch in Streit kommen – ich freue mich darauf –: unter der Führung und Leitung eines starken und guten Präsidiums. Herzlichen Dank.</rede_text>
    <sitzung_datum>2013-10-22</sitzung_datum>
    <redner_vorname>Michael</redner_vorname>
    <redner_nachname>Grosse-Brömer</redner_nachname>
    <redner_fraktion>CDU/CSU</redner_fraktion>
  </speech>
  <speech>
    <rede_text>Danke. – Herr Präsident! Meine Damen und Herren! Herr Grosse-Brömer, Sie streuen hier Brotkrumen und locken uns ein bisschen in die falsche Richtung im Paragrafenwald der Geschäftsordnung. Sie haben quasi am Tag vor der konstituierenden Sitzung des Bundestages öffentlich bekannt gegeben, dass es mehr Vizepräsidentinnen und -präsidenten geben soll. Das wiederum war der Tag nach dem Beschluss über die Aufnahme von Koalitionsverhandlungen. Nun kann ich, was die öffentliche Wahrnehmung angeht, es manchen nicht verübeln, dass das als Geschmäckle, als Deal wahrgenommen wird. Das Zweite. Dies fällt mitten in die Debatte über die Sicherung der Minderheitenrechte der Opposition in diesem Parlament. Ich bedanke mich sehr herzlich für die klaren Worte des Bundestagspräsidenten zu diesen Fragen. Aber Ihre Geste wird von uns nicht als vertrauensbildende Maßnahme wahrgenommen. Festzuhalten bleibt doch – es ist eben gesagt worden –: Der Bundestag wird zurzeit nicht wesentlich größer. Die Aufgaben der Koalition werden nicht wesentlich größer. Im Gegenteil, Sie haben sogar den Vorzug, sich bezüglich ihrer Aufgaben eine wunderbare Arbeitsteilung zu schaffen. Aber die Aufgaben der Opposition werden gewaltig sein, und das bei weniger Abgeordneten. Mithin hat das Bundesverfassungsgericht mehrfach – das ist schon erwähnt worden – die besondere Rolle der Opposition für die Wahrung der freiheitlich-demokratischen Grundordnung betont. Es wird sogar von einer herausgehobenen Stellung der Opposition gesprochen. Das sollten wir uns vor diesem Hintergrund in diesem Hause noch einmal vergegenwärtigen. Nun senden Sie ein fragwürdiges Signal. Es geht nicht nur um einen Vizepräsidentenposten mehr. Es ist Ihr politischer Wille, von der bewährten Praxis in diesem Hause abzuweichen. Sie sagen, die Mehrheitsverhältnisse im Parlament sollten sich im Präsidium abbilden. Das könnte man so hinnehmen. Aber genau in dem entsprechenden Paragrafen der Geschäftsordnung des Bundestages wird überhaupt nicht darauf abgehoben, dass sich im Präsidium das Stärkeverhältnis der Fraktionen abbilden soll. Das ist in dem entsprechenden Paragrafen nicht enthalten. – Nein, Sie können gerne noch einmal nachlesen. Darüber können wir uns im Ältestenrat gerne streiten. Es gibt keinen Bezug auf das Berechnungsverfahren. Es gibt nur die Feststellung, die sich aus der sogenannten Grundmandatsregelung ergibt, dass jede Fraktion mit einem Vizepräsidenten im Präsidium vertreten sein soll. Das ist seit Jahren geübte Praxis in diesem Hause. Es geht um die Repräsentation des gesamten Hauses. Deshalb ist diese Praxis besser und demokratischer. Sie selber haben es vorhin erwähnt: Das, was wir infrage stellen, ist in der 13. Legislaturperiode auf Antrag der Bündnisgrünen eingeführt worden. Auch Sie haben damals als CDU/CDU und FDP ausdrücklich beantragt, dass die Anzahl der Stellvertreterinnen und Stellvertreter bzw. der Vizepräsidentinnen und Vizepräsidenten der Anzahl der Fraktionen entsprechen soll. Nun zur geübten Praxis. Abgesehen von der 1. Legislaturperiode, ist das Präsidium von der 2. bis einschließlich zur 15. Legislaturperiode mit fünf Mitgliedern besetzt gewesen. In der 14. Legislaturperiode waren es sechs. Damals gab es einen Präsidenten, zwei Vizepräsidenten der Koalition und drei Vizepräsidenten der Opposition. Erst in der 16. Legislaturperiode, also zur Zeit der Großen Koalition, ist man davon abgewichen, und es hat einen Vizepräsidenten bzw. eine Vizepräsidentin mehr gegeben. Nun nehmen Sie ausschließlich Bezug auf diese 16. Wahlperiode und gehen von dem zuvor – auch in der letzten Legislaturperiode – angewendeten Prinzip ab und wollen wieder sechs Stellvertreter. Auch damals hatte die SPD zwei Stellvertreter. So richtig geholfen hat es nicht. Das Wahlergebnis der SPD war nicht ganz überzeugend. Gerade erklären Sie von der SPD Ihrer Mitgliederschaft tapfer, dass erst das Ergebnis der Koalitionsverhandlungen darüber entscheidet, ob Sie eine Große Koalition eingehen. Aber den Vizepräsidentenposten wollen Sie schon heute in Anspruch nehmen. Was passiert denn dann, wenn Ihre Basis am Ende sagt: „Der Inhalt der Koalitionsvereinbarung reicht uns nicht; wir wollen keine Große Koalition eingehen“, mit diesem zusätzlichen Vizepräsidentenposten? Diese Frage sollte erlaubt sein. Wie Sie merken, ist vieles in diesem Zusammenhang unklar. Außerdem entsteht der Eindruck, dass es sich hier um eine willkürliche Praxis handelt. Sie klopfen sich sozusagen auf Ihre parlamentarische Brust und warten auf Großraumgeräusche. Wir finden das ziemlich kleingeistig. Ich finde, wir sollten an die gute parlamentarische Praxis anknüpfen. Es besteht auch aufgrund der konkreten Erfahrungen derjenigen, die schon Mitglied des Bundestages waren, überhaupt keine Veranlassung, die Zahl der Vizepräsidenten zu erhöhen. Die demokratische Führung der bisherigen Präsidien nach dem alten Prinzip war gut. Danke schön.</rede_text>
    <sitzung_datum>2013-10-22</sitzung_datum>
    <redner_vorname>Petra</redner_vorname>
    <redner_nachname>Sitte</redner_nachname>
    <redner_fraktion>DIE LINKE</redner_fraktion>
  </speech>
  <speech>
    <rede_text>Herr Präsident! Meine Damen und Herren! Natürlich kann man darüber diskutieren, ob ein Präsidium zu groß oder zu klein ist; aber ich finde, dass ein Präsidium, das aus dem Präsidenten und den Stellvertretern besteht, also in diesem Fall aus sieben Personen bestehen soll, dass also ein siebenköpfiges Präsidium nicht unangemessen groß ist für ein Parlament aus 631 Abgeordneten. Bei der Bildung eines Präsidiums gibt es eigentlich drei Regeln, zwei ungeschriebene und eine, die in unserer Geschäftsordnung steht. In der Geschäftsordnung steht die Grundmandatsklausel. Die erste ungeschriebene Regel ist: Die stärkste Fraktion soll den Präsidenten stellen. Das ist eine Übung im Deutschen Bundestag, der wir immer gefolgt sind. Auch heute haben wir das gemacht. Die geschriebene Regel in der Geschäftsordnung des Deutschen Bundestages, die wir inzwischen angenommen haben, besagt: Jede Fraktion soll unabhängig von ihrer Größe einen Platz im Präsidium bekommen, also ein Grundmandat. Dieses Grundmandat schützt die kleinen Fraktionen. Es ist, wenn man so will, praktizierter Minderheitenschutz. Würde es diese Grundmandatsklausel übrigens nicht geben, wäre auch bei nur fünf Stellvertretern die Verteilung: CDU/CSU zwei, SPD zwei, Linke einer und Grüne null. Mit anderen Worten: Mit der Grundmandatsklausel sichern wir erst einmal die Beteiligung aller Fraktionen im Präsidium. Die dritte Regel ist, dass natürlich das Präsidium auch die Mehrheitsverhältnisse im Parlament abbilden muss. Deshalb werden manchmal ein, manchmal zwei Vizepräsidenten hinzugenommen, um diese Mehrheit darzustellen. Genau das ist hier der Fall: drei für die Union, zwei für die SPD und je einer für die Grünen und für die Linke. Wenn jetzt die geschätzten Kollegen und Kolleginnen von den Grünen sagen, dass im Verhältnis zu ihnen der SPD kein zweiter Vizepräsident zukommen solle, dann kann ich nur sagen: Wir haben beide wirklich nicht gut abgeschnitten bei der Bundestagswahl, aber 25,7 Prozent sind immer noch erkennbar mehr als 8,4 Prozent. Das muss ich den Grünen schon einmal sagen. Ungleiches gleich zu behandeln, ist kein Minderheitenschutz. Aber ich bin schon der Meinung – ich kann das hier für die SPD-Bundestagsfraktion erklären –: Wir sind ohne Einschränkungen gesprächsbereit, wenn es darum geht, die Rechte von Minderheiten im Deutschen Bundestag sicherzustellen, auch wenn wir im Falle der Bildung einer Großen Koalition nur zwei kleine Oppositionsfraktionen haben sollten. Eine parlamentarische Demokratie, die funktioniert, braucht nicht nur eine handlungsfähige Regierung, sondern auch eine effektive Opposition. Für mich ist völlig undenkbar, dass die Opposition nicht in der Lage sein sollte, Anhörungen zu beantragen, Untersuchungsausschüsse auf den Weg zu bringen oder ausreichend Redezeit zu bekommen. Wir werden darüber reden, und wir werden einen Konsens bekommen. Vielen Dank.</rede_text>
    <sitzung_datum>2013-10-22</sitzung_datum>
    <redner_vorname>Thomas</redner_vorname>
    <redner_nachname>Oppermann</redner_nachname>
    <redner_fraktion>SPD</redner_fraktion>
  </speech>
  <speech>

In [39]:
!zip bundestag.zip bundestag.xml

  adding: bundestag.xml (deflated 68%)